services:
  - type: web
    name: house-price-predictor-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "PYTHONPATH=backend uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: SECRET_KEY
        generateValue: true
      - key: FORCE_RETRAIN
        value: false
